# Generated by Django 5.2.10 on 2026-01-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokStreamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tiktok_streamers',
            },
        ),
        migrations.CreateModel(
            name='TikTokComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_user_id', models.CharField(max_length=128)),
                ('tiktok_nickname', models.CharField(max_length=128)),
                ('tiktok_profile_picture', models.URLField(blank=True)),
                ('text', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('tiktok_comment_id', models.CharField(blank=True, max_length=128)),
                ('tiktok_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tiktoklive_listener.tiktokstreamer')),
            ],
            options={
                'db_table': 'tiktok_comments',
                'indexes': [models.Index(fields=['streamer', 'received_at'], name='tiktok_comm_streame_b3cc72_idx'), models.Index(fields=['tiktok_user_id'], name='tiktok_comm_tiktok__c50ce0_idx')],
            },
        ),
    ]
