# Generated by Django 5.2.10 on 2026-01-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktoklive_listener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokListenerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tiktok_listener_config',
            },
        ),
        migrations.AddField(
            model_name='tiktokstreamer',
            name='should_listen',
            field=models.BooleanField(default=False),
        ),
    ]
